import React, { useState } from 'react';

export default function Dashboard() {
  const [activeTab, setActiveTab] = useState('create-lesson');
  const [lessons, setLessons] = useState([]);
  const [loadingQuizId, setLoadingQuizId] = useState(null);
  const [generatedQuizzes, setGeneratedQuizzes] = useState({}); // Stores quiz arrays keyed by lesson ID
  const [formData, setFormData] = useState({
    title: '',
    contentStandard: '',
    indicator: '',
    lessonBody: ''
  });

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmitLesson = (e) => {
    e.preventDefault();
    if (!formData.title || !formData.lessonBody) return;
    
    const newLesson = {
      id: Date.now().toString(),
      created_at: new Date().toLocaleDateString(),
      ...formData
    };
    
    setLessons(prev => [newLesson, ...prev]);
    setFormData({ title: '', contentStandard: '', indicator: '', lessonBody: '' });
    alert('Lesson framework drafted successfully!');
  };

  // Connects directly to the Gemini 3.5 Flash Model using your environment API key
  const handleGenerateQuiz = async (lesson) => {
    const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
    if (!apiKey) {
      alert("Missing API Key configuration. Please verify your environment variables setup.");
      return;
    }

    setLoadingQuizId(lesson.id);
    
    const promptText = `Subject Topic: ${lesson.title}\nStandard: ${lesson.contentStandard}\nIndicator: ${lesson.indicator}\nLesson Body Content:\n${lesson.lessonBody}`;

    try {
      const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=${apiKey}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: promptText }] }],
          generationConfig: {
            responseMimeType: "application/json"
          }
        })
      });

      const data = await response.json();
      const rawText = data.candidates[0].content.parts[0].text;
      
      // Parse out the structured array generated by the AI model
      const quizArray = JSON.parse(rawText);
      
      setGeneratedQuizzes(prev => ({
        ...prev,
        [lesson.id]: quizArray
      }));
    } catch (error) {
      console.error("API Fetch Error:", error);
      alert("Failed to compile quiz structure. Please try again.");
    } finally {
      setLoadingQuizId(null);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col font-sans">
      <header className="bg-indigo-600 text-white p-4 shadow-md">
        <h1 className="text-xl font-bold text-center">EduPlan AI • Lesson & Quiz Studio</h1>
      </header>

      <nav className="flex justify-around bg-white border-b border-gray-200 sticky top-0 z-10">
        <button 
          onClick={() => setActiveTab('create-lesson')}
          className={`flex-1 py-3 text-center font-medium border-b-2 text-sm transition-colors ${
            activeTab === 'create-lesson' ? 'border-indigo-600 text-indigo-600' : 'border-transparent text-gray-500'
          }`}
        >
          Draft Lesson
        </button>
        <button 
          onClick={() => setActiveTab('view-lessons')}
          className={`flex-1 py-3 text-center font-medium border-b-2 text-sm transition-colors ${
            activeTab === 'view-lessons' ? 'border-indigo-600 text-indigo-600' : 'border-transparent text-gray-500'
          }`}
        >
          My Lessons ({lessons.length})
        </button>
      </nav>

      <main className="flex-1 p-4 max-w-md mx-auto w-full">
        {activeTab === 'create-lesson' ? (
          <form onSubmit={handleSubmitLesson} className="bg-white p-5 rounded-xl shadow-sm border border-gray-100 space-y-4">
            <h2 className="text-lg font-semibold text-gray-800">Create Dynamic Lesson Plan</h2>
            
            <div>
              <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Lesson Title</label>
              <input 
                type="text" 
                name="title"
                value={formData.title}
                onChange={handleInputChange}
                placeholder="e.g., Introduction to Vowel Harmony" 
                className="w-full border border-gray-300 rounded-lg p-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                required
              />
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Content Standard</label>
                <input 
                  type="text" 
                  name="contentStandard"
                  value={formData.contentStandard}
                  onChange={handleInputChange}
                  placeholder="e.g., B7.1.1" 
                  className="w-full border border-gray-300 rounded-lg p-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                />
              </div>
              <div>
                <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Indicator</label>
                <input 
                  type="text" 
                  name="indicator"
                  value={formData.indicator}
                  onChange={handleInputChange}
                  placeholder="e.g., B7.1.1.1.2" 
                  className="w-full border border-gray-300 rounded-lg p-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Lesson Core Content / Objectives</label>
              <textarea 
                name="lessonBody"
                value={formData.lessonBody}
                onChange={handleInputChange}
                rows="6" 
                placeholder="Type lesson contents here..." 
                className="w-full border border-gray-300 rounded-lg p-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                required
              ></textarea>
            </div>

            <button type="submit" className="w-full bg-indigo-600 text-white font-medium py-2.5 rounded-lg text-sm shadow">
              Save Lesson Framework
            </button>
          </form>
        ) : (
          <div className="space-y-4">
            <h2 className="text-lg font-semibold text-gray-800">Saved Lesson Plans</h2>
            {lessons.length === 0 ? (
              <div className="text-center py-12 bg-white rounded-xl border border-dashed border-gray-300">
                <p className="text-sm text-gray-400">No lessons stored yet.</p>
              </div>
            ) : (
              lessons.map((lesson) => (
                <div key={lesson.id} className="bg-white p-4 rounded-xl shadow-sm border border-gray-100 space-y-3">
                  <div>
                    <h3 className="font-bold text-gray-900 text-base">{lesson.title}</h3>
                    <p className="text-xs text-indigo-500 font-mono mt-0.5">
                      {lesson.contentStandard && `Standard: ${lesson.contentStandard}`} 
                      {lesson.indicator && ` | Indicator: ${lesson.indicator}`}
                    </p>
                  </div>
                  <p className="text-sm text-gray-600 bg-gray-50 p-2 rounded border border-gray-100 whitespace-pre-wrap">{lesson.lessonBody}</p>
                  
                  {/* Render the AI compiled assessment quiz seamlessly right below the core item row */}
                  {generatedQuizzes[lesson.id] ? (
                    <div className="mt-4 pt-4 border-t border-gray-200 space-y-4">
                      <h4 className="text-xs font-bold text-emerald-600 uppercase tracking-wider">✨ AI Auto-Generated Assessment Quiz</h4>
                      {generatedQuizzes[lesson.id].map((q, qIdx) => (
                        <div key={qIdx} className="bg-emerald-50/50 p-3 rounded-lg border border-emerald-100 space-y-2">
                          <p className="text-sm font-semibold text-gray-800">{qIdx + 1}. {q.question_text}</p>
                          <div className="grid grid-cols-1 gap-1.5 pl-2">
                            {q.options.map((opt, oIdx) => {
                              const letter = String.fromCharCode(65 + oIdx);
                              const isCorrect = letter === q.correct_answer;
                              return (
                                <div key={oIdx} className={`text-xs p-1.5 rounded ${isCorrect ? 'bg-emerald-100 font-medium text-emerald-800 border border-emerald-200' : 'text-gray-600'}`}>
                                  {letter}. {opt} {isCorrect && "✓"}
                                </div>
                              );
                            })}
                          </div>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <div className="pt-2 flex justify-end">
                      <button 
                        onClick={() => handleGenerateQuiz(lesson)}
                        disabled={loadingQuizId === lesson.id}
                        className="text-xs bg-emerald-600 text-white font-medium px-4 py-2 rounded-md shadow-sm active:bg-emerald-700 disabled:opacity-50"
                      >
                        {loadingQuizId === lesson.id ? '⚡ Analyzing Framework...' : '⚡ Auto-Generate Quiz'}
                      </button>
                    </div>
                  )}
                </div>
              ))
            )}
          </div>
        )}
      </main>
    </div>
  );
}
